SOURCES		=	main.cpp 

TARGET		=	../bin/map_random

all:
	g++ -fpermissive -w -o ${TARGET} ${SOURCES}

debug:
	g++ -g3 -fpermissive -w -o ${TARGET}

strict:
	g++ -Wall -o ${TARGET}

dist-clean:
	rm -f ${TARGET}
